macro(cppm_project)
    cmake_parse_arguments(ARG "NIGHTLY;WITH_VCPKG" "" "" ${ARGN})
    if(ARG_WITH_VCPKG)
        set(WITH_VCPKG ON)
    endif()
    if("${CMAKE_TOOLCHAIN_FILE}" STREQUAL "")
        set(CMAKE_TOOLCHAIN_FILE "${CPPM_CORE}/toolchain.cmake")
    else()
        if(CMAKE_TOOLCHAIN_FILE MATCHES "^.*/cppm-tools-.*/toolchain.cmake$")
            set(CMAKE_TOOLCHAIN_FILE "${CPPM_CORE}/toolchain.cmake")
        else()
            set(CPPM_EXTERNAL_TOOLCHAIN_FILE "${CMAKE_TOOLCHAIN_FILE}")
            set(CMAKE_TOOLCHAIN_FILE "${CPPM_CORE}/toolchain.cmake")
        endif()
    endif()
endmacro()
