if(CMAKE_SYSTEM_NAME STREQUAL "Windows" OR (NOT CMAKE_SYSTEM_NAME AND CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows"))
    set(env_home "$ENV{USERPROFILE}")
else()
    set(env_home "$ENV{HOME}")
endif()
string(REPLACE "\\" "/" HOME "${env_home}")
set(CPPM_ROOT   ${HOME}/.cppm)
set(CPPM_PREFIX ${CPPM_ROOT})
set(CPPM_MODULE ${CPPM_ROOT}/cmake)
set(CPPM_CACHE  ${CPPM_ROOT}/cache)
set(CPPM_PKGS   ${CPPM_ROOT}/cppkg)
list(APPEND CMAKE_MODULE_PATH "${CPPM_CORE}")
list(APPEND CMAKE_MODULE_PATH "${CPPM_MODULE}")

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/")
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/Modules/")

include(${CPPM_TOOL}/download/tool)
include(${CPPM_TOOL}/cppm/setting)
include(${CPPM_TOOL}/utility/set_cmake_cache)
include(${CPPM_TOOL}/utility/cppm_print)
include(${CPPM_TOOL}/cppm/cppm_project)
include(${CPPM_TOOL}/cppm/cxx_standard)
include(${CPPM_TOOL}/cppm/compiler_option)
include(${CPPM_TOOL}/cppkg/find)
include(${CPPM_TOOL}/cppm/target_define)
include(${CPPM_TOOL}/cppm/target_dependencies)
include(${CPPM_TOOL}/cppm/target_install)
include(${CPPM_TOOL}/cppkg/download)

